//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accesstokens
    {
        public int idAccesstokens { get; set; }
        public string Token { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int clientid { get; set; }
        public sbyte isAdmin { get; set; }
        public string userid { get; set; }
        public string t_doente { get; set; }
    }
}
