//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int id { get; set; }
        public string name { get; set; }
        public int telecom { get; set; }
        public string gender { get; set; }
        public string birthDate { get; set; }
        public Nullable<bool> deceased { get; set; }
        public string address { get; set; }
        public string photo { get; set; }
        public string maritalStatus { get; set; }
        public string organization { get; set; }
        public Nullable<int> doente { get; set; }
    }
}
