//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPatient
    {
        public int idContactPatient { get; set; }
        public string doente { get; set; }
        public string t_doente { get; set; }
        public int id { get; set; }
        public string relationship { get; set; }
    }
}
