//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_cons_marc
    {
        public string n_cons { get; set; }
        public string t_doente { get; set; }
        public string doente { get; set; }
        public string n_cred { get; set; }
        public string cod_serv { get; set; }
        public string cod_act_med { get; set; }
        public string medico { get; set; }
        public string cod_gab { get; set; }
        public string cod_serv_req { get; set; }
        public Nullable<System.DateTime> dt_cons { get; set; }
        public Nullable<System.DateTime> duracao_cons { get; set; }
        public string flag_estado { get; set; }
        public string observ_cons { get; set; }
    }
}
