//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_doente
    {
        public string t_doente { get; set; }
        public string doente { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> dt_nasc { get; set; }
        public string morada { get; set; }
        public string cod_pais { get; set; }
        public string localidade { get; set; }
        public string cod_postal { get; set; }
        public string telef1 { get; set; }
        public string telef2 { get; set; }
        public string sexo { get; set; }
        public string grupo_sang { get; set; }
        public string escolaridade { get; set; }
        public string raca { get; set; }
        public string religiao { get; set; }
        public string n_bi { get; set; }
        public string n_contrib { get; set; }
        public string nome_mae { get; set; }
        public string nome_pai { get; set; }
        public string estado_civil { get; set; }
        public string nome_conjuge { get; set; }
        public string flag_falec { get; set; }
        public Nullable<System.DateTime> dt_falec { get; set; }
        public string e_mail { get; set; }
        public string cartao_europeu_saude { get; set; }
    }
}
