//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_pess_hosp_def
    {
        public string n_mecan { get; set; }
        public string nome { get; set; }
        public string abr { get; set; }
        public string titulo { get; set; }
        public string email { get; set; }
        public string telef { get; set; }
    }
}
