//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_serv
    {
        public string cod_serv { get; set; }
        public string descr_serv { get; set; }
        public string local_serv { get; set; }
        public string obs { get; set; }
    }
}
