//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class g_t_act_med
    {
        public string cod_serv { get; set; }
        public string cod_act_med { get; set; }
        public string descr { get; set; }
        public Nullable<System.DateTime> dur { get; set; }
    }
}
