//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class glinttlocalEntities : DbContext
    {
        public glinttlocalEntities()
            : base("name=glinttlocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accesstokens> accesstokens { get; set; }
        public DbSet<contact> contact { get; set; }
        public DbSet<contactpatient> contactpatient { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<language> language { get; set; }
        public DbSet<languagecontact> languagecontact { get; set; }
        public DbSet<languagepatient> languagepatient { get; set; }
        public DbSet<languagepractitioner> languagepractitioner { get; set; }
        public DbSet<notifications> notifications { get; set; }
        public DbSet<oauthclients> oauthclients { get; set; }
        public DbSet<patient> patient { get; set; }
        public DbSet<visit> visit { get; set; }
        public DbSet<practitioner> practitioner { get; set; }
    }
}
