//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class glinttEntities : DbContext
    {
        public glinttEntities()
            : base("name=glinttEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<g_cons_marc> g_cons_marc { get; set; }
        public DbSet<g_doente> g_doente { get; set; }
        public DbSet<g_pess_hosp_def> g_pess_hosp_def { get; set; }
        public DbSet<g_serv> g_serv { get; set; }
        public DbSet<g_t_act_med> g_t_act_med { get; set; }
    }
}
