//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Language
    {
        public string language1 { get; set; }
        public string mode { get; set; }
        public string proficiencyLevel { get; set; }
        public Nullable<bool> preference { get; set; }
    }
}
