//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int idNotifications { get; set; }
        public string idDoente { get; set; }
        public string t_doente { get; set; }
        public System.DateTime timestamp { get; set; }
        public string text { get; set; }
        public sbyte seen { get; set; }
        public Nullable<System.DateTime> seentimestamp { get; set; }
    }
}
