//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OauthClients
    {
        public string clientID { get; set; }
        public string clientSecret { get; set; }
        public string responseUri { get; set; }
        public string accessToken { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    }
}
