//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public string doente { get; set; }
        public string t_doente { get; set; }
        public string link { get; set; }
        public Nullable<bool> deceased { get; set; }
        public Nullable<bool> photo { get; set; }
        public string relationship { get; set; }
        public string password { get; set; }
    }
}
