//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practitioner
    {
        public int id { get; set; }
        public Nullable<int> identifier { get; set; }
        public string gender { get; set; }
        public string birthDate { get; set; }
        public Nullable<bool> deceased { get; set; }
        public string address { get; set; }
        public Nullable<bool> photo { get; set; }
        public string maritalStatus { get; set; }
        public string code { get; set; }
        public string period { get; set; }
        public Nullable<bool> issuer { get; set; }
        public string password { get; set; }
    }
}
