//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int id { get; set; }
        public string setting { get; set; }
        public Nullable<System.DateTime> periodEnd { get; set; }
        public Nullable<int> id_contact { get; set; }
        public Nullable<int> admitter { get; set; }
        public string bed { get; set; }
        public Nullable<int> discharger { get; set; }
    }
}
